[package]
name = "router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.9"
http-body-util = "0.1.0-rc.2"
hyper = { version = "0.14.25", features = ["full"] }
opentelemetry = { version = "0.19.0", features = ["rt-tokio"] }
opentelemetry-http = { version = "0.8.0", features = ["hyper", "tokio", "reqwest"] }
opentelemetry-jaeger = { version = "0.18.0", features = [
    "rt-tokio",
], default-features = false }
redis = "0.22.3"
tokio = { version = "1.26.0", features = ["full"] }
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = "0.1.37"
tracing-opentelemetry = { version = "0.18.0", features = ["async-trait"] }
tracing-subscriber = "0.3.16"
